format = '''
$directory$git_branch
$character'''

palette = 'colors'

[palettes.colors]
mustard = '#af8700'
color1 = '{{colors.primary_fixed_dim.default.hex}}'
color2 = '{{colors.on_primary.default.hex}}'
color3 = '{{colors.on_surface_variant.default.hex}}'
color4 = '{{colors.surface_container.default.hex}}'
color5 = '{{colors.on_primary.default.hex}}'
color6 = '{{colors.surface_dim.default.hex}}'
color7 = '{{colors.surface.default.hex}}'
color8 = '{{colors.primary.default.hex}}'
color9 = '{{colors.tertiary.default.hex}}'

[character]
success_symbol = "[ğŸˆ](color9 bold)"
error_symbol = "[ğŸˆ](red)"
vicmd_symbol = "[ğŸˆ](color3)"

[directory]
format = "[$path](fg:color1)"
truncation_length = 3

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[git_branch]
symbol = " ï˜ "
format = "[$symbol$branch](fg:color3)"

[time]
disabled = true
